
### login get jwt

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
   "username": "user",
   "password": "user123!"
}



### home

GET http://localhost:8080
#Authorization: Basic user user123!

### authInfo

GET http://localhost:8080/authInfo
#Authorization: Basic user user123!
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ1c2VyIiwiaWF0IjoxNzI2MjI4ODQxLCJleHAiOjE3MjYzMTUyNDF9.Vxzxcjs1goN4it9XuxNyAJlt-UtUyDZflwI3oRspO7CXO1K5QOuqeY0XXlIob-9P


### api/hello

GET http://localhost:8080/api/hello
Authorization: Basic admin admin123!

### ex

GET http://localhost:8080/ex

### 創建一個新的 Todo
POST http://localhost:8080/api/todos
Authorization: Basic admin admin123!
Content-Type: application/json

{
  "title": "學習 Spring Boot",
  "completed": false
}

### 獲取所有 Todo
GET http://localhost:8080/api/todos
Authorization: Basic admin admin123!

### 獲取 ID 為 1 的 Todo
GET http://localhost:8080/api/todos/1
Authorization: Basic admin admin123!

### 更新 ID 為 1 的 Todo
PUT http://localhost:8080/api/todos/1
Authorization: Basic admin admin123!
Content-Type: application/json

{
  "title": "精通 Spring Boot cash",
  "completed": true
}

### 刪除 ID 為 1 的 Todo
DELETE http://localhost:8080/api/todos/1
Authorization: Basic admin admin123!


### search
GET http://localhost:8080/api/todos/search?keyword=cash

### completd
GET http://localhost:8080/api/todos/completed

### count-incomplete
GET http://localhost:8080/api/todos/count-incomplete


### paging
GET http://localhost:8080/api/todos/paged

### paging, page 1
GET http://localhost:8080/api/todos/paged?page=1


### paging and sort id desc
GET http://localhost:8080/api/todos/paged?page=0&sortBy=id&direction=desc

### paging and sort id desc, page 1
GET http://localhost:8080/api/todos/paged?page=1&sortBy=id&direction=desc





### default
GET http://localhost:8080/query01?name={{$random.alphanumeric(8)}}

### @RequestParam
GET http://localhost:8080/query02?name={{$random.alphanumeric(8)}}

### @RequestParam with default
GET http://localhost:8080/query03

### @PathVariable
GET http://localhost:8080/path01/{{$random.alphanumeric(8)}}

### @PathVariable with defaut, it is worng way
GET http://localhost:8080/path02/

### @PathVariable with defaut, it is right way
GET http://localhost:8080/path03

### header
GET http://localhost:8080/header
name:1234

### cookie
GET http://localhost:8080/cookie
Cookie: name=abc123

### default
POST http://localhost:8080/form01
Content-Type: application/x-www-form-urlencoded

title = abc01

### @RequestParam
POST http://localhost:8080/form02
Content-Type: application/x-www-form-urlencoded

title = abc02

### binding to object
POST http://localhost:8080/form03
Content-Type: application/x-www-form-urlencoded

title = abc03

### @RequestParam bindint to map
POST http://localhost:8080/form04
Content-Type: application/x-www-form-urlencoded

title = abc04

### @RequestBody binding to object
POST http://localhost:8080/body01
Content-Type: application/json

{
  "title": "body 01"
}

### @RequestBody binding to map
POST http://localhost:8080/body02
Content-Type: application/json

{
  "title": "body 02"
}

### file
POST http://localhost:8080/file
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="text.txt"
Content-Type: text/plain

i am file content
--WebAppBoundary--
