
### 創建一個新的 Todo
POST http://localhost:8080/api/todos
Content-Type: application/json

{
  "title": "學習 Spring Boot",
  "completed": false
}

### 獲取所有 Todo
GET http://localhost:8080/api/todos

### 獲取 ID 為 1 的 Todo
GET http://localhost:8080/api/todos/1

### 更新 ID 為 1 的 Todo
PUT http://localhost:8080/api/todos/1
Content-Type: application/json

{
  "title": "精通 Spring Boot",
  "completed": true
}

### 刪除 ID 為 1 的 Todo
DELETE http://localhost:8080/api/todos/1


## Query String Parameter

### default
GET http://localhost:8080/query01?name={{$random.alphanumeric(8)}}

### @RequestParam
GET http://localhost:8080/query02?name={{$random.alphanumeric(8)}}

### @RequestParam with default
GET http://localhost:8080/query03

## Path Variables

### @PathVariable
GET http://localhost:8080/path01/{{$random.alphanumeric(8)}}

### @PathVariable with defaut, it is worng way
GET http://localhost:8080/path02/

### @PathVariable with defaut, it is right way
GET http://localhost:8080/path03

## header and cookie

### header
GET http://localhost:8080/header
name:1234

### cookie
GET http://localhost:8080/cookie
Cookie: name=abc123

## form data

### default
POST http://localhost:8080/form01
Content-Type: application/x-www-form-urlencoded

title = abc01

### @RequestParam
POST http://localhost:8080/form02
Content-Type: application/x-www-form-urlencoded

title = abc02

### Object
POST http://localhost:8080/form03
Content-Type: application/x-www-form-urlencoded

title = abc03

### @RequestParam Map
POST http://localhost:8080/form04
Content-Type: application/x-www-form-urlencoded

title = abc04

## request body

### @RequestBody
POST http://localhost:8080/body01
Content-Type: application/json

{
  "title": "body 01"
}

###
POST http://localhost:8080/body02
Content-Type: application/json

{
  "title": "body 02"
}
